version: '3.8'

services:
    server:
        image: "nginx:stable-alpine" # alpine - clean compressed version
        ports:
            - "8000:80"
        volumes:
            - ./server/nginx.conf:/etc/nginx/conf.d/default.conf:ro # :ro - read only
            - ./src/laravel:/var/www/laravel
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        depends_on:
            - db
            - php
            - adminer
    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src/laravel:/var/www/laravel
    db:
        image: mysql:8.0
        restart: always
        ports:
            - "3316:3306"
        env_file:
            - env/db.env
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql
            - ./env/my.cnf:/etc/mysql/my.cnf

    adminer:
        image: adminer
        restart: always
        ports:
            - "6080:8080"

    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - ./src/laravel/:/var/www/laravel
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        working_dir: ${APP_PATH_CONTAINER}
        command: composer install

    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src/laravel:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]